/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import vistas.alumno.Formulario;

/**
 *
 * @author Ulymay
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        //El desktop es el panel por defecto
        setContentPane(desktop);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumno = new javax.swing.JMenu();
        menuAlumnoAdd = new javax.swing.JMenuItem();
        menuAlumnoEdit = new javax.swing.JMenuItem();
        menuAlumnoDelete = new javax.swing.JMenuItem();
        menuAlumnoLst = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        menuAlumno.setText("Alumnos");

        menuAlumnoAdd.setText("Agregar");
        menuAlumnoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumnoAddActionPerformed(evt);
            }
        });
        menuAlumno.add(menuAlumnoAdd);

        menuAlumnoEdit.setText("Editar");
        menuAlumnoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumnoEditActionPerformed(evt);
            }
        });
        menuAlumno.add(menuAlumnoEdit);

        menuAlumnoDelete.setText("Eliminar");
        menuAlumno.add(menuAlumnoDelete);

        menuAlumnoLst.setText("Listado");
        menuAlumno.add(menuAlumnoLst);

        jMenuBar1.add(menuAlumno);

        jMenu2.setText("Cursos");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Maestros");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAlumnoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnoAddActionPerformed
        Formulario falumno = new Formulario(true);
        falumno.setVisible(true);
        desktop.add(falumno);
    }//GEN-LAST:event_menuAlumnoAddActionPerformed

    private void menuAlumnoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnoEditActionPerformed
        Formulario falumno = new Formulario(false);
        falumno.setVisible(true);
        desktop.add(falumno);
    }//GEN-LAST:event_menuAlumnoEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenuItem menuAlumnoAdd;
    private javax.swing.JMenuItem menuAlumnoDelete;
    private javax.swing.JMenuItem menuAlumnoEdit;
    private javax.swing.JMenuItem menuAlumnoLst;
    // End of variables declaration//GEN-END:variables
}
